<a href="https://colab.research.google.com/github/mrtchlpck/project-1-lecture/blob/main/gotowa_wersja_notatnika_M1_assignment_2026_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Travelling tracks: group assignment

**Group:** _number_ · **Members:** _names_

Replace that line before you hand this in. The three questions are in
[assignment.md](../courses/ds4b-m1-3-pandas-2026/assignment.md), and also on the Moodle page.

This template has the data loading, the headings, and a place to write each answer. Work
through it top to bottom: run the setup, then for each question fill in the code cells and
then the answer block underneath. Delete each prompt comment once you have answered it.

Before you hand in: **Restart & Run All**. If it doesn't run start to finish in a clean
kernel, it isn't done.

In [242]:
# Setup. This cell is given to you; you should not need to change it.
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print(f"pandas {pd.__version__}")
print(f"numpy {np.__version__}")

# The two data files. These URLs work anywhere, Colab included.
SONGS_URL = "https://raw.githubusercontent.com/aaubs/ds-master/codex/m1-pandas-2026/data/M1_2026/spotify_songs.csv"
FAMILIES_URL = "https://raw.githubusercontent.com/aaubs/ds-master/codex/m1-pandas-2026/data/M1_2026/subgenre_families.csv"


def load_class_csv(filename, url):
    """Read a class data file: the local copy if there is one, otherwise the URL above."""
    candidates = [Path("data/M1_2026") / filename,
                  Path("../data/M1_2026") / filename,
                  Path("ds-master/data/M1_2026") / filename,
                  Path("../ds-master/data/M1_2026") / filename]
    for path in candidates:
        if path.exists():
            print(f"Loaded {filename} from {path}")
            return pd.read_csv(path)
    print(f"Loaded {filename} from {url}")
    return pd.read_csv(url)


songs_raw = load_class_csv("spotify_songs.csv", SONGS_URL)
families_raw = load_class_csv("subgenre_families.csv", FAMILIES_URL)

print(f"songs_raw:    {songs_raw.shape[0]:,} rows x {songs_raw.shape[1]} columns")
print(f"families_raw: {families_raw.shape[0]:,} rows x {families_raw.shape[1]} columns")

pandas 2.2.3
numpy 2.1.3
Loaded spotify_songs.csv from https://raw.githubusercontent.com/aaubs/ds-master/codex/m1-pandas-2026/data/M1_2026/spotify_songs.csv
Loaded subgenre_families.csv from https://raw.githubusercontent.com/aaubs/ds-master/codex/m1-pandas-2026/data/M1_2026/subgenre_families.csv
songs_raw:    32,833 rows x 23 columns
families_raw: 24 rows x 2 columns

In [243]:
songs = songs_raw.copy()
families = families_raw.copy()

songs["playlist_subgenre"] = (
    songs["playlist_subgenre"]
    .astype("string")
    .str.strip()
    .str.lower()
)

families["subgenre"] = (
    families["subgenre"]
    .astype("string")
    .str.strip()
    .str.lower()
)

## Question 1 · What is one row, and how far does each track travel?

In [244]:
# What one row of songs_raw is. Show the output, not just the claim.
#how does the raw row look like in this table -> one row is just one song on one playlist
print(songs.columns.tolist())
display(songs.head(2))
print("Unique tracks:", songs["track_id"].nunique())
print("Unique playlists:", songs["playlist_id"].nunique())

['track_id', 'track_name', 'track_artist', 'track_popularity', 'track_album_id', 'track_album_name', 'track_album_release_date', 'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms']

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.1020,0.00000,0.0653,0.518,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.0724,0.00421,0.3570,0.693,99.972,162600

Unique tracks: 28356
Unique playlists: 471

In [245]:
# Your working table, and evidence its rows are what you say they are.
#here we make our working table so every song only once here
unique_tracks = (songs.drop_duplicates("track_id").copy())
print(unique_tracks.shape)
display(unique_tracks.head(2))

#to check if all tracks are unique
unique_tracks["track_id"].nunique()
print(unique_tracks.shape)
print(unique_tracks["track_id"].is_unique)

(28356, 23)

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.1020,0.00000,0.0653,0.518,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.0724,0.00421,0.3570,0.693,99.972,162600

(28356, 23)
True

In [246]:
# Playlists per track, and the check that it counts playlists.

#we count playlists not raw rows so we use nunique
playlist_counts = (
    songs
    .groupby("track_id")["playlist_id"]
    .nunique()
    .reset_index(name="playlist_count")
)
playlist_counts.head(3)

#we add this playlist_counts to our working table
unique_tracks = unique_tracks.merge(
    playlist_counts,
    on="track_id",
    how="left",
    validate="one_to_one"
)
#we can see some song are in 2/3 playlists, we check
print(unique_tracks.shape)
print(unique_tracks["track_id"].is_unique)
print(unique_tracks[["track_id", "playlist_count"]].head(10))

(28356, 24)
True
                 track_id  playlist_count
0  6f807x0ima9a1j3VPbc7VN               2
1  0r7CVbZTWZgbTCYdfa2P31               2
2  1z1Hg7Vb0AhHDiEmnDE79l               3
3  75FpbthrwQmzHlBJLuGdC7               1
4  1e8PAfcKUYoKkxPhrHqw4x               1
5  7fvUMiyapMsRRxr07cU8Ef               3
6  2OAylPUDDfwRGfe0lYqlCQ               1
7  6b1RNvAcJjQH73eZO4BLAB               2
8  7bF6tCO3gFb8INrEDcjNT5               3
9  1IXGILkPm0tOCNeq00kCPa               2

In [247]:
# What's missing in the columns you'll use, and what the release dates record.
cols = ["track_id", "playlist_id", "playlist_name", "track_name", "track_album_release_date"]
unique_tracks[cols].isna().sum()
#we use only cols that we use in our analysis, so track and playlists name and id and release date

track_id                    0
playlist_id                 0
playlist_name               0
track_name                  4
track_album_release_date    0
dtype: int64

In [248]:
# A release year you can defend. Question 3 wants one.
unique_tracks["track_album_release_date"].dropna().head(5)

0    2019-06-14
1    2019-12-13
2    2019-07-05
3    2019-07-19
4    2019-03-05
Name: track_album_release_date, dtype: object

In [249]:
# here we make a new column where we only look at the year of the release date, we don"t change the one that is in the table
unique_tracks["release_year"] = (
    unique_tracks["track_album_release_date"].
    astype("string").
    str[:4].
    astype("Int64"))

#we check if it works
print(unique_tracks[["track_album_release_date", "release_year"]].head(5))
print(unique_tracks.shape)
print(unique_tracks["track_id"].is_unique)

  track_album_release_date  release_year
0               2019-06-14          2019
1               2019-12-13          2019
2               2019-07-05          2019
3               2019-07-19          2019
4               2019-03-05          2019
(28356, 25)
True

### Question 1 answers

Fill these in. One or two sentences each, in your own words.

**One row of the raw file is:**

**One row of our working table is:** ... and we chose that because ...

**We counted playlists per track using:** ... **The check that convinced us it counts
playlists:** ...

**Missing values in the columns we use:** ... **What we did about each:** ...

**The release dates record ... precision, so the year we derived is ...** and what we would
have been inventing by parsing them all to a full day is ...

## Question 2 · Attach the family label

Write your predicted row count down before you merge.

In [250]:
# Rows you expect after the merge (write it down before you run the next cell):
# we look how many rows we had, we should not have more after the merge
print("Expected rows:", unique_tracks.shape[0])

Expected rows: 28356

In [251]:
print(families.columns.tolist()) #we check what is the name for subgenre in this table
print(unique_tracks.columns.tolist()) #we check what is the name for subgenre in this table

['subgenre', 'family']
['track_id', 'track_name', 'track_artist', 'track_popularity', 'track_album_id', 'track_album_name', 'track_album_release_date', 'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'playlist_count', 'release_year']

In [252]:
print(families["subgenre"].duplicated().sum()) #we check how many duplicated subgenre we have
print(
    families[
        families["subgenre"].duplicated(keep=False)
    ][["subgenre", "family"]]
    .sort_values("subgenre")
)

1
     subgenre           family
1   dance pop  club_electronic
16  dance pop        pop_craft

In [253]:
#we check how many conflicts we have
conflicts = (
    families
    .groupby("subgenre")["family"]
    .nunique()
    .reset_index(name="n_families")
)

print(conflicts[conflicts["n_families"] > 1])

    subgenre  n_families
3  dance pop           2

In [254]:
#we don"t want to guess where should dance pop be, so we make the table where dance pop will be NaN so that there would be no confusion
families_new = families[
    families["subgenre"] != "dance pop"
]

In [255]:
# The merge, with validate= and indicator=.
merged = unique_tracks.merge(
    families_new[["subgenre", "family"]],
    left_on="playlist_subgenre",
    right_on="subgenre",
    how="left",
    validate="many_to_one",
    indicator=True
)
#merged = unique_tracks.merge(
    #families_new,
    #left_on="playlist_subgenre",
    #right_on="subgenre",
    #how="left",
    #validate="many_to_one",
    #indicator=True
#)
#we check if rows are the same before and after the merge
print(unique_tracks.shape)
print(merged.shape)
display(merged.head(3))
print(merged[["playlist_subgenre", "family"]].isna().sum())
display(
    merged[["playlist_subgenre", "family"]].tail(10)
)

(28356, 25)
(28356, 28)

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,instrumentalness,liveness,valence,tempo,duration_ms,playlist_count,release_year,subgenre,family,_merge
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.000000,0.0653,0.518,122.036,194754,2,2019,<NA>,NaN,left_only
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.004210,0.3570,0.693,99.972,162600,2,2019,<NA>,NaN,left_only
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.000023,0.1100,0.613,124.008,176616,3,2019,<NA>,NaN,left_only

playlist_subgenre       0
family               2456
dtype: int64

               playlist_subgenre           family
28346  progressive electro house  club_electronic
28347  progressive electro house  club_electronic
28348  progressive electro house  club_electronic
28349  progressive electro house  club_electronic
28350  progressive electro house  club_electronic
28351  progressive electro house  club_electronic
28352  progressive electro house  club_electronic
28353  progressive electro house  club_electronic
28354  progressive electro house  club_electronic
28355  progressive electro house  club_electronic

In [256]:
print(merged["_merge"].value_counts())
print(
    merged.loc[
        merged["family"].isna(),
        "playlist_subgenre"
    ].value_counts()
)

_merge
both          25900
left_only      2456
right_only        0
Name: count, dtype: int64
playlist_subgenre
dance pop    1298
tropical     1158
Name: count, dtype: Int64

In [257]:
print(families[families["subgenre"] == "neo soul"])
print(families[families["subgenre"] == "dance pop"])
print(families[families["subgenre"] == "tropical"])

    subgenre    family
21  neo soul  soul_rnb
     subgenre           family
1   dance pop  club_electronic
16  dance pop        pop_craft
Empty DataFrame
Columns: [subgenre, family]
Index: []

In [258]:
display(families)
#neo soul is written in big letter that is the problem
#there is no tropical

                     subgenre           family
0                    big room  club_electronic
1                   dance pop  club_electronic
2               electro house  club_electronic
3                     pop edm  club_electronic
4   progressive electro house  club_electronic
5                  album rock      guitar_rock
6                classic rock      guitar_rock
7                   hard rock      guitar_rock
8              permanent wave      guitar_rock
9                gangster rap   hiphop_lineage
10                    hip hop   hiphop_lineage
11              latin hip hop   hiphop_lineage
12           southern hip hop   hiphop_lineage
13                       trap   hiphop_lineage
14                  latin pop     latin_rhythm
15                  reggaeton     latin_rhythm
16                  dance pop        pop_craft
17                 electropop        pop_craft
18            indie poptimism        pop_craft
19              post-teen pop        pop_craft
20                    hip pop         soul_rnb
21                   neo soul         soul_rnb
22             new jack swing         soul_rnb
23         urban contemporary         soul_rnb

In [259]:
# What's wrong with the keys?

In [260]:
# What you decided, and what each decision costs.

### Question 2 answers

**Rows we predicted after the merge:** ... **Rows we got:** ...

**What is wrong with the keys:**

**What we decided about each problem, and what it cost:**

**Rows with no family label at the end:** ... **What we did with them:**

## Question 3 · Do travelling tracks differ?

In [261]:
# Travelling versus not. Counts next to every mean.

In [262]:
# Move the cut-off. At least three.

In [263]:
# Inside each family. Which ones are too thin to carry it?

In [264]:
# Do the two groups differ in release year? What does that do to popularity?

In [265]:
# Reshape, then one chart.

### Question 3 answers

**We defined travelling as:** ... **because** ...

**The comparison, with counts:** (paste or describe your summary table)

**What changed when we moved the cut-off:**

**Families too thin to carry the comparison:**

**A better grouping than the supplied families would have been:**

**Do the two groups differ in release year, and what does that do to the popularity result:**

### Interpretation

_250 to 400 words: what you found, what it's resting on, and two things this data can't
tell the curation team._

## Decision log

One line per question. What you decided, and what it cost.

| Question | Decision | What it cost |
|---|---|---|
| 1 · Rows and reach | | |
| 2 · The join | | |
| 3 · Cut-off and comparison | | |

## Tools we used

_Which ones, what for. The condition is that you can explain any line you hand in, and
you're about to present it._

## Before handing in

- [ ] Group number and names in the first cell
- [ ] Restart & Run All, clean kernel, produces this notebook
- [ ] Three questions, in order, prompt comments deleted
- [ ] Decision log filled in
- [ ] Everyone speaks in the video, on a different decision